import { LogicContext } from "types";
import { LogicActionCustomAction, LogicActionMergeComponentSchema, LogicActionProperty, LogicActionPropertyBoolean, LogicActionPropertyString, LogicActionValue } from "types/AdvancedLogic";
export declare const hasLogic: (context: LogicContext) => boolean;
export declare const checkTrigger: (context: LogicContext, trigger: any) => boolean;
export declare function setActionBooleanProperty(context: LogicContext, action: LogicActionPropertyBoolean): boolean;
export declare function setActionStringProperty(context: LogicContext, action: LogicActionPropertyString): boolean;
export declare function setActionProperty(context: LogicContext, action: LogicActionProperty): boolean;
export declare function setValueProperty(context: LogicContext, action: LogicActionValue): boolean;
export declare function setMergeComponentSchema(context: LogicContext, action: LogicActionMergeComponentSchema): boolean;
export declare function setCustomAction(context: LogicContext, action: LogicActionCustomAction): boolean;
export declare const applyActions: (context: LogicContext) => boolean;
