import { ProcessorFn, ProcessorFnSync, ProcessorInfo, ValidationContext, ValidationProcessorFn, ValidationProcessorFnSync, ValidationRuleInfo, ValidationScope, SkipValidationFn } from "types";
import { ConditionallyHidden } from "processes/conditions";
export declare function validationRules(context: ValidationContext, rules: ValidationRuleInfo[], skipValidation?: SkipValidationFn): ValidationRuleInfo[];
export declare function isInputComponent(context: ValidationContext): boolean;
export declare function isValueHidden(context: ValidationContext): boolean;
export declare function isForcedHidden(context: ValidationContext, isConditionallyHidden: ConditionallyHidden): boolean;
export declare const _shouldSkipValidation: (context: ValidationContext, isConditionallyHidden: ConditionallyHidden) => boolean;
export declare const shouldSkipValidationCustom: SkipValidationFn;
export declare const shouldSkipValidationSimple: SkipValidationFn;
export declare const shouldSkipValidation: SkipValidationFn;
export declare function shouldValidateAll(context: ValidationContext): boolean;
export declare function shouldValidateCustom(context: ValidationContext): boolean;
export declare function shouldValidateServer(context: ValidationContext): boolean;
export declare const validateProcess: ValidationProcessorFn;
export declare const validateProcessSync: ValidationProcessorFnSync;
export declare const validateCustomProcess: ValidationProcessorFn;
export declare const validateCustomProcessSync: ProcessorFnSync<ValidationScope>;
export declare const validateServerProcess: ValidationProcessorFn;
export declare const validateServerProcessSync: ProcessorFnSync<ValidationScope>;
export declare const validateAllProcess: ProcessorFn<ValidationScope>;
export declare const validateAllProcessSync: ProcessorFnSync<ValidationScope>;
export declare const validateCustomProcessInfo: ProcessorInfo<ValidationContext, void>;
export declare const validateServerProcessInfo: ProcessorInfo<ValidationContext, void>;
export declare const validateProcessInfo: ProcessorInfo<ValidationContext, void>;
export * from './util';
