import { ProcessorFn, ProcessorFnSync, ConditionsScope, ProcessorInfo, DefaultValueContext } from 'types';
export declare const hasCustomDefaultValue: (context: DefaultValueContext) => boolean;
export declare const hasServerDefaultValue: (context: DefaultValueContext) => boolean;
export declare const hasDefaultValue: (context: DefaultValueContext) => boolean;
export declare const customDefaultValueProcess: ProcessorFn<ConditionsScope>;
export declare const customDefaultValueProcessSync: ProcessorFnSync<ConditionsScope>;
export declare const serverDefaultValueProcess: ProcessorFn<ConditionsScope>;
export declare const serverDefaultValueProcessSync: ProcessorFnSync<ConditionsScope>;
export declare const defaultValueProcess: ProcessorFn<ConditionsScope>;
export declare const defaultValueProcessSync: ProcessorFnSync<ConditionsScope>;
export declare const customDefaultValueProcessInfo: ProcessorInfo<DefaultValueContext, void>;
export declare const serverDefaultValueProcessInfo: ProcessorInfo<DefaultValueContext, void>;
export declare const defaultValueProcessInfo: ProcessorInfo<DefaultValueContext, void>;
