import { ProcessorFn, ProcessorFnSync, ConditionsScope, ProcessorInfo, ConditionsContext } from 'types';
export declare const hasConditions: (context: ConditionsContext) => boolean;
export declare const isCustomConditionallyHidden: (context: ConditionsContext) => boolean;
export declare const isSimpleConditionallyHidden: (context: ConditionsContext) => boolean;
export declare const isConditionallyHidden: (context: ConditionsContext) => boolean;
export type ConditionallyHidden = (context: ConditionsContext) => boolean;
export declare const conditionalProcess: (context: ConditionsContext, isHidden: ConditionallyHidden) => false | undefined;
export declare const customConditionProcess: ProcessorFn<ConditionsScope>;
export declare const customConditionProcessSync: ProcessorFnSync<ConditionsScope>;
export declare const simpleConditionProcess: ProcessorFn<ConditionsScope>;
export declare const simpleConditionProcessSync: ProcessorFnSync<ConditionsScope>;
export declare const conditionProcess: ProcessorFn<ConditionsScope>;
export declare const conditionProcessSync: ProcessorFnSync<ConditionsScope>;
export declare const customConditionProcessInfo: ProcessorInfo<ConditionsContext, void>;
export declare const simpleConditionProcessInfo: ProcessorInfo<ConditionsContext, void>;
export declare const conditionProcessInfo: ProcessorInfo<ConditionsContext, void>;
